services:
  api:
    image: ghcr.io/luscaer/ean13-generator-api:latest
    restart: unless-stopped
    networks:
      - proxy-network
  
  spa:
    image: ghcr.io/luscaer/ean13-generator-spa:latest
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true